name: bus_tracking_system
description: Smart Transport & Bus Tracking System
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:

  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.0
  firebase_storage: ^11.7.0

  # Maps + GPS
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0

  # Login
  google_sign_in: ^6.2.1

  # Face verification
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.10.0
  image_picker: ^1.1.2

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/bus.png